### ISSUE TITLE
question 

### ISSUE THREAD

**Issue by FathiMahdi** [FASKA2003/STM32_Bootloader#1]
can this boot loader work for bank memory structure like STM32G0B1

**Comment by itsmahfoudi** [comment]
Hi Mahdi,
Yes, I guess you have just to adapt it, because in my case the flash memory
was 512kb single bank divided into 8 sectors, what it is important is that
the bootloader code is placed in the first 2 sectors (0 and 1), take that
into consideration, when you want to place the application code.
